# Generated by Django 4.1 on 2022-10-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='accepted_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default='automatic selection', max_length=70),
        ),
    ]
