# Generated by Django 4.1 on 2022-10-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_location_doctor_specialization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='location',
            new_name='city',
        ),
    ]
