# Generated by Django 4.1 on 2022-11-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_rename_location_doctor_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_experience',
            field=models.IntegerField(default=0),
        ),
    ]
