# Generated by Django 4.1 on 2022-11-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctor_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='cost_per_visit',
            field=models.IntegerField(default=0),
        ),
    ]
